### ISSUE TITLE
Cannot seem to get past login

### ISSUE THREAD

**Issue by melono6** [aartek/spotify-chromecast-player#2]
I can't seem to login although im sure my user/pass are definitely correct..
i get errorInvalidCredentials

I am testing using a nest hub. i see spotify opens correctly but then i get the above error.

I have tried to receive an access token other ways (https://developer.spotify.com/documentation/general/guides/authorization-guide/)
and then passing the token through to the 'setCredentials' send function
but as soon as i send the token spotify seems to just close on the device.

**Comment by melono6** [comment]
managed to solve part of my problem...
seems the setCreditials needs the token expiration eg
`that.send({
	type: 'setCredentials',
	credentials: credentials.access_token, 
	expiresIn: credentials.expiration,
});`

**Comment by kosimst** [comment]
Hi, I am currently struggling with the same problem. I passed acces token and expiresIn (=3600) and yet spotify terminates on the device. I obtained the access token with all scopes I can think of. How could you solve your problem?
Thanks in advance, Simon

**Comment by melono6** [comment]
I have not had much time to work on this last couple days. But i got 1 part of the puzzle..
if you login to spotify web player and check the network tab. look for the xhr request to get_access_token
youll see something like the following in the response:
`
{
    "clientId":"xxxx",
    "accessToken":"xxxx-xxx-xxx-xxx",
    "accessTokenExpirationTimestampMs":1610636440248,
    "isAnonymous":false
}
` 
using the accessToken and accessTokenExpirationTimestampMs in the setCredentials will log me in correctly.

im yet to determine much further than this. such as how long that token will live for and how to get it programatically

**Comment by kosimst** [comment]
Ok, nice, thank you. I am going to try to build a middleware to fetch this token, as soon as I made any progress I will post it here.

**Comment by kosimst** [comment]
I think the problem is the captcha, I tried it using Puppeteer, which worked just fine.
